name: Greeting from acer

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a name
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Sai
          MIDDLE_NAME: Sivamani
          LAST_NAME: Karthik
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
